### PR TITLE
Update book sale link to new /about page

### PR DESCRIPTION
**Pull request by Nierot**
Please add the following information to your pull request:

**Please describe what your PR is fixing**
Since studystore does not sell books anymore, I have made a /about page with the current book list. This should only be merged when Q4 has been added.

**Concretely, which issues does your PR solve? (Please reference them by typing `Fixes/References Inter-Actief/amelie#<issue_id>`)**
#729 

**Does your PR change how we process personal data, impact our [privacy document](https://www.inter-actief.utwente.nl/privacy/), or modify (one of) our data export(s)?**
no

**Does your PR include any django migrations?**
no

**Does your PR include the proper translations (did you add translations for new/modified strings)?**
no, my PR does not include translations

**Does your PR include CSS changes (and did you run the `compile_css.sh` script in the `scripts` directory to regenerate the `compiled.css` file)?**
no, my PR does not include CSS changes

**Does your PR need external actions by for example the System Administrators? (Think about new pip packages, new (local) settings, a new regular task or cronjob, new management commands, etc.)?**
no

**Did you properly test your PR before submitting it?**
yes

### CODE REVIEW

**Review by Kurocon — APPROVED** [review]

**Comment by Kurocon** [comment]
@Nierot Is this still WIP or ready to merge?

**Comment by Nierot** [comment]
for now still WIP since we still need to figure out what information can be published under the study store book contract. hope to know more this week

**Comment by Kurocon** [comment]
> for now still WIP since we still need to figure out what information can be published under the study store book contract. hope to know more this week

Any updates?

**Comment by Nierot** [comment]
This can be merged!

**Pull request merged**
